references:
  ucsc:
    GRCh37:
      fasta: ucsc/GRCh37/hg19.p13.plusMT.no_alt_analysis_set.fa
    GRCh38:
      fasta: ucsc/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
  ncbi:
    GRCh37:
      fasta: ncbi/GRCh37/human_g1k_v37.fasta
    GRCh38:
      fasta: ncbi/GRCh38/GRCh38.primary.fa
chain:
  hg19ToHg38: chain/hg19ToHg38.over.chain.gz
  hg38ToHg19: chain/hg38ToHg19.over.chain.gz
